version: '3.8'
services:

  # Application Service
  app:
    container_name: app
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
      target: dev-build
    image: app
    volumes:
      - ./src:/var/www/html
    ports:
      - "4444:9000"
    working_dir: /var/www/html

  # Web Server Service
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    image: nginx
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./src/public:/var/www/html/public


  # Database
  db:
    image: mariadb:latest
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_USER: 'main'
      MYSQL_PASSWORD: 'password'
      MYSQL_DATABASE: 'sinov8-laravel'
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql

  #phpMyAdmin Service
  hpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "3400:80"
    depends_on:
      - db


  node:
      build:
        context: .
        dockerfile: ./docker/node/Dockerfile
      image: node
      volumes:
        - ./src:/var/www/html
